config/routes.rb
Rails.application.routes.draw do
  get "chat/message"
  resources :experiences, except: [ :index, :show ]
  resource :session
  resources :passwords, param: :token
  resources :projects, except: [ :index, :show ]
  root "home#index"
  post '/chat/message', to: 'chat#message'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/experience.rb
class Experience < ApplicationRecord
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ edit update destroy ]

  def new
    @experience = Experience.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to root_path, notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @experience.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, status: :see_other, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to root_path, notice: "Experience was successfully created." }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def experience_params
      params.expect(experience: [ :title, :organization, :start_date, :end_date, :description, :location ])
    end


end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_experience.html.erb
<div id="<%= dom_id experience %>" class="w-full sm:w-auto my-5">
  <div class="flex gap-2 items-center">
    <div class="font-bold text-xl">
      <%= experience.title %>
    </div>
    <div>
      <%= experience.organization %>
    </div>
    <div>
      <%= experience.location %>
    </div>
    <% if authenticated? %>
      <%= link_to edit_experience_path(experience) do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
          <path d="m5.433 13.917 1.262-3.155A4 4 0 0 1 7.58 9.42l6.92-6.918a2.121 2.121 0 0 1 3 3l-6.92 6.918c-.383.383-.84.685-1.343.886l-3.154 1.262a.5.5 0 0 1-.65-.65Z" />
          <path d="M3.5 5.75c0-.69.56-1.25 1.25-1.25H10A.75.75 0 0 0 10 3H4.75A2.75 2.75 0 0 0 2 5.75v9.5A2.75 2.75 0 0 0 4.75 18h9.5A2.75 2.75 0 0 0 17 15.25V10a.75.75 0 0 0-1.5 0v5.25c0 .69-.56 1.25-1.25 1.25h-9.5c-.69 0-1.25-.56-1.25-1.25v-9.5Z" />
        </svg>
      <% end %>
      <%= link_to experience, method: :delete, data: { "turbo-method": :delete } do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="size-5">
          <path d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z" />
        </svg>
      <% end %>
    <% end %>
  </div>
  <div class="">
    <div>
      <%= experience.description %>
    </div>
  </div>
  <div class="flex gap-2">
    <div>
      <%= experience.start_date %>
    </div>
    -
    <div>
      <%= experience.end_date %>
    </div>
  </div>
</div>

app/views/experiences/_form.html.erb
<%= form_with(model: experience, class: "contents") do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul class="list-disc ml-6">
        <% experience.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experience.errors[:title].none?, "border-red-400 focus:outline-red-600": experience.errors[:title].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :organization %>
    <%= form.text_field :organization, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experience.errors[:organization].none?, "border-red-400 focus:outline-red-600": experience.errors[:organization].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experience.errors[:start_date].none?, "border-red-400 focus:outline-red-600": experience.errors[:start_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experience.errors[:end_date].none?, "border-red-400 focus:outline-red-600": experience.errors[:end_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experience.errors[:description].none?, "border-red-400 focus:outline-red-600": experience.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :location %>
    <%= form.text_field :location, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experience.errors[:location].none?, "border-red-400 focus:outline-red-600": experience.errors[:location].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<% content_for :title, "Editing experience" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing experience</h1>

  <%= render "form", experience: @experience %>

  <%= link_to "Show this experience", @experience, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to experiences", experiences_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/experiences/new.html.erb
<% content_for :title, "New experience" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New experience</h1>

  <%= render "form", experience: @experience %>

  <%= link_to "Back to experiences", experiences_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>